### ISSUE TITLE
Possible to alternate between Rx and Tx ?

### ISSUE THREAD

**Issue by perkasajob** [mruijter/lora_transceiver#3]
it works great and helped me a lot , I have problem how to alternate between Tx and Rx, if Rx fifo is receiving, and then Tx Fifo is written, it freezes, I haven't fully grasp how the whole thing working. thank you.

**Comment by mruijter** [comment]
Hi Perkasajob,

While the transmitter is transmitting the receiver is blocked and vice versa. The hardware does not allow full-duplex operation.

**Comment by perkasajob** [comment]
Thank You !
